spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: todo

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todo}
    username: ${SPRING_DATASOURCE_USERNAME:todo}
    password: ${SPRING_DATASOURCE_PASSWORD:todo}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.portfolio.todo
  type-handlers-package: com.portfolio.todo.mybatis.typehandler
  configuration:
    map-underscore-to-camel-case: true
